//* translation:  */
let currentTheme = 'light';

let currentLanguage = 'en';


const translations = {
    en: {
        navHome: "Home",
        navAbout: "About",
        navOurTravel: "Our Travel",
        navHoneymoonPackages: "Honeymoon Packages",
        navToursPackages: "Tours Packages",
        navMusicalEvents: "Musical Events",
        navBuildPackage: "Build Package",
        navBuildYourOwnPackage: "Build Your Own Package",
        navEnterDestination: "Enter destination (country, region or city)",
        navTwoAdults: "2 adults",
        navOneAdult: "1 adult",
        navThreeAdults: "3 adults",
        navFourAdults: "4 adults",
        navActivitiesPreferences: "Activities preferences (optional)",
        navCulture: "Culture",
        navOutdoors: "Outdoors",
        navRelaxing: "Relaxing",
        navWildlife: "Wildlife",
        navRomantic: "Romantic",
        navReligious: "Religious",
        navHiking: "Hiking",
        navMusical: "Musical",
        navShopping: "Shopping",
        navBusiness: "Business",
        navMuseums: "Museums",
        navParty: "Party",
        navTraditions: "Traditions",
        navWalks: "Walks",
        navFishing: "Fishing",
        navCruise: "Cruise",
        navExplore: "Explore",
        navUpcomingTravel: "Upcoming Travel",
        navLoginForm: "Login Form",
        navSignInToAccount: "Sign in to your account",
        navEmail: "Email",
        navPassword: "Password",
        navForgotYourPassword: "Forgot your password?",
        navLoginAsAdmin: "Login As Admin",
        navDontHaveAnAccount: "Don't have an account?",
        navSignUp: "Sign up",
        navMakeANewAccount: "Make a new account",
        navConfirmPassword: "Confirm Password",
        navAlreadyHaveAnAccount: "Already have an account?",
        navUsername: "Username",
        navLogin: "Login",
        navNoMatter: "No matter",
        navWhereYouAreGoingTo: "where you're going to, we'll take you there",
        navTravelType: "Travel Type",
        navAdventure: "Adventure",
        navRelaxation: "Relaxation",
        navExploration: "Exploration",
        navDuration: "Duration",
        nav1To3Days: "1-3 Days",
        nav4To7Days: "4-7 Days",
        nav1To2Weeks: "1-2 Weeks",
        navSubmit: "Submit",
        navPeopleBooked: "people booked Tomorrowland Event in the last 24 hours",
        sectionFastEasy: "Fast & Easy",
        sectionGetYourFavouriteResortBookings: "Get Your Favourite Resort Bookings",
        sectionChooseDestination: "Choose Destination",
        sectionCheckAvailability: "Check Availability",
        sectionLetsGo: "Let's Go",
        sectionStepDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna, tortor tempus.",
        sectionLetsMakeYourNextHolidayAmazing: "Let’s Make Your Next Holiday Amazing",
        sectionPromotion: "Promotion",
        sectionWeProvideYouBestEuropeSightseeingTours: "We Provide You Best Europe Sightseeing Tours",
        sectionEtLaboreHarum: "Et labore harum non nobis ipsum eum molestias mollitia et corporis praesentium a laudantium...",
        sectionViewPackages: "View Packages",
        // ====================================
        navTrendy: "Trendy",
        navOurTrendingTravel: "Our Trending Travel",
        navWhatClientsSay: "What Clients Say",
        navTravelDescription: "Travel helps companies manage payments easily.",
        navCompany: "Company",
        navAboutUs: "About Us",
        navCareers: "Careers",
        navBlog: "Blog",
        navPricing: "Pricing",
        navDestinations: "Destinations",
        navMaldives: "Maldives",
        navLosAngeles: "Los Angeles",
        navLasVegas: "Las Vegas",
        navToronto: "Toronto",
        navJoinOurNewsletter: "Join Our Newsletter",
        navSubscribe: "Subscribe",
        navNewsletterDescription: "Will send you weekly updates for your better tour packages.",
        navCopyright: "Copyright @ Travel Team 2024. All Rights Reserved.",
        navPromotion: "Promotion",
        navBestEuropeTours: "We Provide You Best Europe Sightseeing Tours",
        navDescription: "Et labore harum non nobis ipsum eum molestias mollitia et corporis praesentium a laudantium internos. Non quis eius quo eligendi corrupti et fugiat nulla qui soluta recusandae in maxime quasi aut ducimus illum aut optio quibusdam!",
        navViewPackages: "View Packages",
        navTrend: "Trend",
        navPopularTourPlans: "Our Popular Tour Plans",
        navDescriptionTrend: "Et labore harum non nobis ipsum eum molestias mollitia et corporis praesentium a laudantium. Et labore harum non nobis ipsum eum molestias mollitia et corporis praesentium a laudantium.",
        navVacations: "Vacations",
        navHoneymoon: "Honeymoon",
        navMusicalEvents: "MUSICAL EVENTS",
        navExploreMore: "Explore more",
        navOurInternationalPackages: "Our International Packages",
        navRead: "READ",
        navAboutUsTitle: "About Us",
        navSearchTour: "Search Tour",
        navTravelWithUs: "Travel With Us",
        navDate: "Date",
        navPriceLowToHigh: "price low to High",
        navPriceHighToLow: "Price High to low",
        navNameAZ: "Name (A-z)",
        navSwitzerland: "Switzerland",
        navBerlin: "Berlin",
        navMaldives: "Maldives",
        navToronto: "Torronto",
        navBaku: "Baku",
        navChinese: "Chinese",
        navCardDate: "12, September 2022",
        navCardPeople: "120+ People",
        navCardDescription: "Qui Tempore Voluptate Qui Quia Commodi Rem Praesentium Alias Et.",
        navViewNow: "View Now",
        planYourTrip: "Plan Your Trip",
    formDescription: "A unique selection of destinations with a comfortable experience.",
    searchTour: "Search Tour",
    whereTo: "Where To?",
    date: "Date",
    filterByPrice: "Filter By Price",
    priceRange: "Price: $12 - $3600",
    bookNow: "Book Now",
    information: "Information",
    tourPlan: "Tour Plan",
    location: "Location",
    gallery: "Gallery",
    bookThisTour: "Book This Tour",
    formDescription: "A unique selection of destinations with a comfortable experience.",
    nameLabel: "Name",
    emailLabel: "Your Email",
    phoneLabel: "Phone",
    tourDateLabel: "Date Of The Tour",
    ticketNumberLabel: "Number of Tickets",
    messageLabel: "Message",
    checkAvailability: "Check Availability",
    bookNow: "Book Now",
 searchTour: "Search Tour",
        travelWithUs: "Travel With Us",
        toronto: "Toronto",
        price: "2,000 $",
        perCouple: "Per Couple",
        reviews: "(4k review)",
        torontoDescription: `Toronto is the largest city in Canada and the capital of Ontario. Located on the northwestern shore of Lake Ontario, 
          it is a major financial and commercial hub. The city is known for its cultural diversity, with residents from various nationalities. 
          Toronto features many attractions such as the CN Tower and Toronto Islands. The cultural life is rich, with numerous theaters, museums, 
          and festivals. It is also a major center for higher education, hosting several prestigious universities and colleges.`,
        destination: "Destination",
        departure: "Departure",
        departureTime: "Departure Time",
        returnTime: "Return Time",
        dressCode: "Dress Code",
        notIncluded: "Not Included",
        included: "Included",
        galleryTicket: "Gallery Ticket",
        lunch: "Lunch",
        fiveStarAccommodation: "5 star Accommodations",
        airportTransfer: "Airport Transfer",
        breakfast: "Breakfast",
        personalGuide: "Personal Guide",
        fromGallery: "From our gallery",
        cnTowerDescription: "The CN Tower offers sweeping views of Toronto’s skyline and Lake Ontario. Capture the cityscape from the observation deck, especially during sunset for a breathtaking panorama. It’s a must-visit for any photographer.",
        bookTourTitle: "Book This Tour",
    bookTourDescription: "Ex optio sequi et quos praesentium in nostrum labore nam rerum iusto aut magni nesciunt? Quo quidem neque iste expedita est dolo.",
    labelName: "Name",
    labelEmail: "Your Email",
    labelPhone: "Phone",
    labelDate: "Date Of The Tour",
    labelTickets: "Number of Tickets",
    labelMessage: "Message",
    checkAvailability: "Check Availability",
    bookNow: "Book Now",
    information: "Information",
    tourPlan: "Tour Plan",
    location: "Location",
    gallery: "Gallery",
    information: "Information",
    tour_plan: "Tour Plan",
    location: "Location",
    gallery: "Gallery",
    day1_name: "Day 1: Departure",
    day1_desc: "Depart for Toronto, explore the iconic CN Tower, marvel at marine life in Ripley’s Aquarium, and stroll along the vibrant Harbourfront.",
    day1_feature1: "5 Star Accommodation",
    day1_feature2: "Breakfast",
    day2_name: "Day 2: Visiting Zurich, Geneva and Zermatt",
    day2_desc: "Visit the Royal Ontario Museum, discovering diverse exhibits, and the Art Gallery of Ontario, admiring impressive art collections.",
    day2_feature1: "5 Star Accommodation",
    day2_feature2: "Breakfast",
    day3_name: "Day 3: Rest",
    day3_desc: "Discover the historic Distillery District, with its charming cobblestone streets, and the bustling St. Lawrence Market, sampling local delicacies.",
    day3_feature1: "5 Star Accommodation",
    day3_feature2: "Breakfast",
    day4_name: "Day 4: Historical Tour",
    day4_desc: "Spend time at Toronto Islands, enjoying outdoor activities and stunning skyline views, perfect for a relaxing day.",
    day4_feature1: "5 Star Accommodation",
    day4_feature2: "Breakfast",
    day5_name: "Day 5: Return",
    day5_desc: "Take a day trip to Niagara Falls, experiencing the majestic waterfalls and exploring the surrounding attractions before returning home.",
    book_this_tour: "Book This Tour",
    form_desc: "Ex optio sequi et quos praesentium in nostrum labore nam rerum iusto aut magni nesciunt? Quo quidem neque iste expedita est dolo.",
    name_label: "Name",
    email_label: "Your Email",
    phone_label: "Phone",
    date_label: "Date Of The Tour",
    number_label: "Number of Tickets",
    message_label: "Message",
    check_availability: "Check Availability",
    book_now: "Book Now",
    location: "Location",
        cityDescription: "Toronto, the capital of Ontario, Canada, is located on the northwestern shore of Lake Ontario. It is the largest city in Canada and a major international hub for business, finance, arts, and culture. Toronto’s skyline is dominated by the iconic CN Tower, offering panoramic views of the city and the lake.",
        culturalScene: "The city is known for its multicultural population, with vibrant neighborhoods such as Chinatown, Little Italy, and Greektown. Toronto’s cultural scene is rich and diverse, featuring world-class museums, theaters, and music venues. The Royal Ontario Museum and the Art Gallery of Ontario are must-visit attractions. The city’s extensive park system, including High Park and the Toronto Islands, provides ample opportunities for outdoor activities. Toronto’s culinary scene is equally diverse, offering a wide range of international cuisines. The city’s efficient public transportation system makes it easy to explore its many attractions.",
        bookTour: "Book This Tour",
        bookTourDescription: "Ex optio sequi et quos praesentium in nostrum labore nam rerum iusto aut magni nesciunt? Quo quidem neque iste expedita est dolo.",
        name: "Name",
        yourEmail: "Your Email",
        phone: "Phone",
        dateOfTour: "Date Of The Tour",
        numberOfTickets: "Number of tickets",
        message: "Message",
        checkAvailability: "Check Availability",
        bookNow: "Book Now",
        info: "Information",
        tour_plan: "Tour Plan",
        location: "Location",
        gallery: "Gallery",
        location_title: "Location",
        toronto_description: "Toronto, the capital of Ontario, Canada, is located on the northwestern shore of Lake Ontario. It is the largest city in Canada and a major international hub for business, finance, arts, and culture. Toronto’s skyline is dominated by the iconic CN Tower, offering panoramic views of the city and the lake.",
        cultural_scene: "The city is known for its multicultural population, with vibrant neighborhoods such as Chinatown, Little Italy, and Greektown. Toronto’s cultural scene is rich and diverse, featuring world-class museums, theaters, and music venues. The Royal Ontario Museum and the Art Gallery of Ontario are must-visit attractions. <br><br>The city’s extensive park system, including High Park and the Toronto Islands, provides ample opportunities for outdoor activities. Toronto’s culinary scene is equally diverse, offering a wide range of international cuisines. The city’s efficient public transportation system makes it easy to explore its many attractions.",
        book_tour_title: "Book This Tour",
        booking_description: "Ex optio sequi et quos praesentium in nostrum labore nam rerum iusto aut magni nesciunt? Quo quidem neque iste expedita est dolo.",
        name_label: "Name",
        email_label: "Your Email",
        phone_label: "Phone",
        date_label: "Date Of The Tour",
        number_label: "Number of Tickets",
        message_label: "Message",
        check_availability: "Check Availability",
        book_now: "Book Now",


    },
    ar: {
        info: "معلومات",
        tour_plan: "خطة الجولة",
        location: "موقع",
        gallery: "معرض",
        location_title: "موقع",
        toronto_description: "تورنتو، عاصمة أونتاريو، كندا، تقع على الشاطئ الشمالي الغربي لبحيرة أونتاريو. إنها أكبر مدينة في كندا ومركز دولي رئيسي للأعمال والتمويل والفنون والثقافة. يهيمن برج CN الأيقوني على أفق تورنتو، مما يوفر مناظر بانورامية للمدينة والبحيرة.",
        cultural_scene: "تشتهر المدينة بتنوع سكانها، مع أحياء نابضة بالحياة مثل الحي الصيني، وإيطاليا الصغيرة، وحي اليونان. مشهد تورنتو الثقافي غني ومتعدد الثقافات، مع وجود متاحف عالمية المستوى، ومسارح، وأماكن موسيقية. يعد متحف أونتاريو الملكي ومعرض أونتاريو للفنون من المعالم التي يجب زيارتها. <br><br>يوفر النظام البيئي الشامل في المدينة، بما في ذلك حديقة هاي بارك وجزر تورنتو، فرصًا واسعة للأنشطة الخارجية. مشهد الطهي في تورنتو متنوع أيضًا، حيث يقدم مجموعة واسعة من المأكولات الدولية. يسهل نظام النقل العام الفعال في المدينة استكشاف العديد من المعالم.",
        book_tour_title: "احجز هذه الجولة",
        booking_description: "أكز خيارًا يتبع ويمثل في مختبرنا ما هي رغبتنا في الأعمال.",
        name_label: "الاسم",
        email_label: "بريدك الإلكتروني",
        phone_label: "الهاتف",
        date_label: "تاريخ الجولة",
        number_label: "عدد التذاكر",
        message_label: "رسالة",
        check_availability: "تحقق من التوافر",
        book_now: "احجز الآن",
        location: "الموقع",
        cityDescription: "تورونتو، عاصمة أونتاريو، كندا، تقع على الشاطئ الشمالي الغربي لبحيرة أونتاريو. إنها أكبر مدينة في كندا ومركز دولي رئيسي للأعمال والمالية والفنون والثقافة. يهيمن برج سي إن الأيقوني على أفق تورونتو، مما يوفر إطلالات بانورامية على المدينة والبحيرة.",
        culturalScene: "تشتهر المدينة بتنوع سكانها، مع أحياء نابضة بالحياة مثل الحي الصيني، وإيطاليا الصغيرة، ومدينة اليونان. المشهد الثقافي في تورونتو غني ومتعدد الأوجه، ويضم متاحف عالمية المستوى، والمسارح، وأماكن الموسيقى. يجب زيارة متحف أونتاريو الملكي ومعرض أونتاريو الفني. يوفر نظام الحدائق الواسع في المدينة، بما في ذلك حديقة هاي بارك وجزر تورونتو، فرصًا واسعة للأنشطة الخارجية. كما أن المشهد الطهوي في المدينة متنوع تمامًا، حيث يقدم مجموعة واسعة من المأكولات العالمية. يسهل نظام النقل العام الفعال في المدينة استكشاف العديد من معالمها.",
        bookTour: "احجز هذه الجولة",
        bookTourDescription: "إكس أوبتيوا سيكوي إيتي كوس برايسنتيوم إن نوستروم لابور نام ريروم إيوسيتو أوت ماجني نيسكيونت؟ كوا كوييديم نيكي إستي إكسبيديتا إيست دولو.",
        name: "الاسم",
        yourEmail: "بريدك الإلكتروني",
        phone: "الهاتف",
        dateOfTour: "تاريخ الجولة",
        numberOfTickets: "عدد التذاكر",
        message: "رسالة",
        checkAvailability: "تحقق من التوفر",
        bookNow: "احجز الآن",
        information: "معلومات",
        tour_plan: "خطة الجولة",
        location: "الموقع",
        gallery: "معرض الصور",
        day1_name: "اليوم الأول: المغادرة",
        day1_desc: "غادر إلى تورونتو، استكشاف برج CN الأيقوني، والتأمل في الحياة البحرية في حوض أسماك ريبلي، والتنزه على طول المرفأ النابض بالحياة.",
        day1_feature1: "إقامة 5 نجوم",
        day1_feature2: "إفطار",
        day2_name: "اليوم الثاني: زيارة زيورخ، جنيف، وزيرمات",
        day2_desc: "زيارة متحف أونتاريو الملكي، واكتشاف معارض متنوعة، ومعرض الفنون بأونتاريو، والاستمتاع بمجموعات فنية رائعة.",
        day2_feature1: "إقامة 5 نجوم",
        day2_feature2: "إفطار",
        day3_name: "اليوم الثالث: الراحة",
        day3_desc: "اكتشاف حي التقطير التاريخي بشوارعه المرصوفة بالحصى، وسوق سانت لورانس الصاخب لتذوق المأكولات المحلية.",
        day3_feature1: "إقامة 5 نجوم",
        day3_feature2: "إفطار",
        day4_name: "اليوم الرابع: جولة تاريخية",
        day4_desc: "قضاء الوقت في جزر تورونتو، والتمتع بالأنشطة الخارجية وإطلالات خلابة على الأفق، مناسبة ليوم مريح.",
        day4_feature1: "إقامة 5 نجوم",
        day4_feature2: "إفطار",
        day5_name: "اليوم الخامس: العودة",
        day5_desc: "القيام برحلة نهارية إلى شلالات نياغرا، مع الاستمتاع بالشلالات المهيبة واستكشاف المعالم المحيطة قبل العودة إلى المنزل.",
        book_this_tour: "احجز هذه الجولة",
        form_desc: "مثال على الوصف هنا، عمل لوريم إيبسوم.",
        name_label: "الاسم",
        email_label: "البريد الإلكتروني",
        phone_label: "الهاتف",
        date_label: "تاريخ الجولة",
        number_label: "عدد التذاكر",
        message_label: "الرسالة",
        check_availability: "تحقق من التوافر",
        book_now: "احجز الآن",

        information: "معلومات",
    tourPlan: "خطة الجولة",
    location: "الموقع",
    gallery: "معرض الصور",
    // Tour days
    day1Name: "اليوم الأول: المغادرة",
    day1Description: "الانطلاق إلى تورنتو واستكشاف برج CN الشهير، والانبهار بالحياة البحرية في أكواريوم Ripley’s، والتجول على طول Harbourfront النابض بالحياة.",
    day2Name: "اليوم الثاني: زيارة زيورخ وجنيف وزيرمات",
    day2Description: "زيارة متحف أونتاريو الملكي، واستكشاف المعارض المتنوعة، ومعرض أونتاريو للفنون، والإعجاب بالمجموعات الفنية المثيرة للإعجاب.",
    day3Name: "اليوم الثالث: الراحة",
    day3Description: "اكتشاف منطقة Distillery التاريخية بشوارعها المرصوفة بالحصى وسوق سانت لورنس الصاخب وتذوق المأكولات المحلية.",
    day4Name: "اليوم الرابع: جولة تاريخية",
    day4Description: "قضاء وقت في جزر تورنتو والتمتع بالأنشطة الخارجية والمناظر الخلابة لأفق المدينة، مثالي ليوم مريح.",
    day5Name: "اليوم الخامس: العودة",
    day5Description: "القيام برحلة ليوم واحد إلى شلالات نياجرا، واستكشاف الشلالات المهيبة والمعالم المحيطة قبل العودة إلى المنزل.",
    accommodation: "إقامة 5 نجوم",
    breakfast: "إفطار",
    
        bookTourTitle: "احجز هذه الجولة",
        bookTourDescription: "استمتع بتجربة استثنائية مع فرصة لا مثيل لها لزيارة المواقع الرائعة. لا تفوت هذه الفرصة.",
        labelName: "الاسم",
        labelEmail: "بريدك الإلكتروني",
        labelPhone: "رقم الهاتف",
        labelDate: "تاريخ الجولة",
        labelTickets: "عدد التذاكر",
        labelMessage: "الرسالة",
        checkAvailability: "تحقق من التوفر",
        bookNow: "احجز الآن",
 toronto: "تورنتو",
    price: "2000 $",
    perCouple: "لكل زوجين",
    reviews: "(4 آلاف مراجعة)",
    torontoDescription: `تورنتو هي أكبر مدينة في كندا وعاصمة مقاطعة أونتاريو. تقع على الشاطئ الشمالي الغربي لبحيرة أونتاريو، 
      وهي مركز مالي وتجاري رئيسي. المدينة معروفة بتنوعها الثقافي، حيث يعيش بها سكان من جنسيات مختلفة. 
      تتميز تورنتو بالعديد من المعالم السياحية مثل برج CN وجزر تورنتو. الحياة الثقافية فيها غنية، مع العديد من المسارح والمتاحف والمهرجانات. 
      كما أنها مركز كبير للتعليم العالي، حيث تستضيف عدة جامعات وكليات مرموقة.`,
    destination: "الوجهة",
    departure: "المغادرة",
    departureTime: "وقت المغادرة",
    returnTime: "وقت العودة",
    dressCode: "الزي المطلوب",
    notIncluded: "غير متضمن",
    included: "متضمن",
    galleryTicket: "تذكرة المعرض",
    lunch: "الغداء",
    fiveStarAccommodation: "إقامة 5 نجوم",
    airportTransfer: "النقل من المطار",
    breakfast: "الإفطار",
    personalGuide: "دليل شخصي",
    fromGallery: "من معرضنا",
    cnTowerDescription: "يقدم برج CN إطلالات بانورامية على أفق تورنتو وبحيرة أونتاريو. التقط المدينة من سطح المراقبة، ,خاصةً أثناء غروب الشمس للحصول على منظر مذهل. إنه معلم لا بد من زيارته لأي مصور.",
  

searchTour: "ابحث عن جولة",
        travelWithUs: "سافر معنا",
        planYourTrip: "خطط رحلتك",
    formDescription: "اختيار مميز للوجهات مع تجربة مريحة.",
    searchTour: "ابحث عن جولة",
    whereTo: "إلى أين؟",
    date: "تاريخ",
    filterByPrice: "تصفية حسب السعر",
    priceRange: "السعر: 12$ - 3600$",
    bookNow: "احجز الآن",
    information: "معلومات",
    tourPlan: "خطة الجولة",
    location: "الموقع",
    gallery: "المعرض",
    bookThisTour: "احجز هذه الجولة",
    formDescription: "اختيار مميز للوجهات مع تجربة مريحة.",
    nameLabel: "الاسم",
    emailLabel: "بريدك الإلكتروني",
    phoneLabel: "رقم الهاتف",
    tourDateLabel: "تاريخ الجولة",
    ticketNumberLabel: "عدد التذاكر",
    messageLabel: "رسالة",
    checkAvailability: "تحقق من التوافر",
    bookNow: "احجز الآن",
        navViewNow: "عرض الآن",
        navCardDescription: "تتضمن باقاتنا تجارب فريدة ومتنوعة في الوجهات المختارة.",
        navCardPeople: "120+ شخص",
        navCardDate: "12 سبتمبر 2022",
        navChinese: "الصين",
        navBaku: "باكو",
        navToronto: "تورونتو",
        navMaldives: "مالديف",
        navBerlin: "برلين",
        navSwitzerland: "سويسرا",
        navNameAZ: "الاسم (أ-ي)",
        navPriceHighToLow: "السعر من الأعلى إلى الأقل",
        navPriceLowToHigh: "السعر من الأقل إلى الأعلى",
        navDate: "تاريخ",
        navTravelWithUs: "سافر معنا",
        navSearchTour: "بحث عن جولة",
        navAboutUsTitle: "معلومات عنا",
        navRead: "اقرأ",
        navOurInternationalPackages: "حفلاتنا الدولية",
        navExploreMore: "استكشف المزيد",
        navMusicalEvents: "الفعاليات الموسيقية",
        navHoneymoon: "شهر العسل",
        navVacations: "العطلات",
        navDescriptionTrend: "وتمتاز خدماتنا بتقديم أفضل التجارب السياحية التي نالت شهرة واسعة. نحن هنا لنساعدك في اكتشاف المعالم السياحية الفريدة والمميزة.",
        navPopularTourPlans: "خطط جولاتنا المشهورة",
        navTrend: "المشهورة",
        navViewPackages: "عرض الباقات",
        navDescription: "وتمتاز خدماتنا بتقديم أفضل التجارب السياحية في أوروبا. نحن هنا لنساعدك في اكتشاف المعالم السياحية الفريدة والمميزة.",
        navBestEuropeTours: "نقدم لك أفضل جولات مشاهدة المعالم في أوروبا",
        navPromotion: "ترويج",
        navCopyright: "حقوق الطبع والنشر @ فريق السفر 2024. جميع الحقوق محفوظة.",
        navNewsletterDescription: "سنرسل لك تحديثات أسبوعية لتحسين باقات السفر الخاصة بك.",
        navSubscribe: "اشترك",
        navJoinOurNewsletter: "انضم إلى نشرتنا الإخبارية",
        navToronto: "تورونتو",
        navLasVegas: "لاس فيغاس",
        navLosAngeles: "لوس أنجلوس",
        navMaldives: "جزر المالديف",
        navDestinations: "وجهات السفر",
        navPricing: "الأسعار",
        navBlog: "مدونة",
        navCareers: "وظائف",
        navAboutUs: "معلومات عنا",
        navCompany: "شركة",
        navTravelDescription: "السفر يساعد الشركات في إدارة المدفوعات بسهولة.",
        navWhatClientsSay: "ماذا يقول العملاء",
        navOurTrendingTravel: "سفرنا العصري",
        navTrendy: "عصري",
        // ===================================================
        navHome: "الصفحة الرئيسية",
        navAbout: "حول",
        navOurTravel: "رحلاتنا",
        navHoneymoonPackages: "باقات شهر العسل",
        navToursPackages: "الرحلات",
        navMusicalEvents: "الفعاليات الموسيقية",
        navBuildPackage: "إنشاء رحلة",
        navBuildYourOwnPackage: "إنشاء باقتك الخاصة",
        navEnterDestination: "أدخل الوجهة (البلد، المنطقة أو المدينة)",
        navTwoAdults: "2 بالغين",
        navOneAdult: "1 بالغ",
        navThreeAdults: "3 بالغين",
        navFourAdults: "4 بالغين",
        navActivitiesPreferences: "تفضيلات الأنشطة (اختياري)",
        navCulture: "ثقافة",
        navOutdoors: "الأنشطة الخارجية",
        navRelaxing: "استرخاء",
        navWildlife: "الحياة البرية",
        navRomantic: "رومانسي",
        navReligious: "ديني",
        navHiking: "المشي لمسافات طويلة",
        navMusical: "موسيقي",
        navShopping: "تسوق",
        navBusiness: "أعمال",
        navMuseums: "متاحف",
        navParty: "حفلة",
        navTraditions: "تقاليد",
        navWalks: "نزهات",
        navFishing: "صيد الأسماك",
        navCruise: "رحلة بحرية",
        navExplore: "استكشاف",
        navUpcomingTravel: "السفر القادم",
        navLoginForm: "نموذج تسجيل الدخول",
        navSignInToAccount: "تسجيل الدخول إلى حسابك",
        navEmail: "البريد الإلكتروني",
        navPassword: "كلمة المرور",
        navForgotYourPassword: "نسيت كلمة المرور؟",
        navLoginAsAdmin: "تسجيل الدخول كمسؤول",
        navDontHaveAnAccount: "ليس لديك حساب؟",
        navSignUp: "إنشاء حساب",
        navMakeANewAccount: "إنشاء حساب جديد",
        navConfirmPassword: "تأكيد كلمة المرور",
        navAlreadyHaveAnAccount: "هل لديك حساب بالفعل؟",
        navUsername: "اسم المستخدم",
        navLogin: "تسجيل الدخول",
        navNoMatter: "لا يهم",
        navWhereYouAreGoingTo: "إلى أين أنت ذاهب، سنأخذك هناك",
        navTravelType: "نوع السفر",
        navAdventure: "مغامرة",
        navRelaxation: "استرخاء",
        navExploration: "استكشاف",
        navDuration: "المدة",
        nav1To3Days: "1-3 أيام",
        nav4To7Days: "4-7 أيام",
        nav1To2Weeks: "1-2 أسابيع",
        navSubmit: "إرسال",
        navPeopleBooked: "شخصًا قاموا بحجز حدث تومورولاند في الساعات الـ 24 الماضية",
        sectionFastEasy: "سريع وسهل",
        sectionGetYourFavouriteResortBookings: "احصل على حجوزات المنتجعات المفضلة لديك",
        sectionChooseDestination: "اختر الوجهة",
        sectionCheckAvailability: "تحقق من التوافر",
        sectionStepDescription: "نص تجريبي لتوضيح خطوات الحجز.",
        sectionLetsGo: "لنذهب",
        sectionLetsMakeYourNextHolidayAmazing: "دعنا نجعل عطلتك القادمة مذهلة",
        sectionWeProvideYouBestEuropeSightseeingTours: "نقدم لك أفضل جولات مشاهدة معالم أوروبا",
        sectionPromotion: "عرض",
        sectionEtLaboreHarum: "وتمتاز بكونها خالية من المتاعب ، حيث نقوم بتوفير كل ما تحتاجه للاستمتاع برحلتك.",
        sectionViewPackages: "عرض الرحلات",
        
        
        
        
    },

};

function setLanguage(language) {
    const textElements = translations[language];

     // العثور على جميع العناصر التي تحتوي على خاصية data-translate
        const translateElements = document.querySelectorAll("[data-translate]");

        translateElements.forEach((element) => {
            const keyOfLanguage = element.getAttribute("data-translate"); // الحصول على المفتاح
            if (textElements[keyOfLanguage]) {
                element.textContent = textElements[keyOfLanguage]; // تعيين النص بناءً على المفتاح
            }
        });
    currentLanguage = language; // Update the current language
    localStorage.setItem("language", language); // تخزين اللغة المختارة في localStorage

    const dropdowns = document.querySelectorAll(".dropdown-menu");

    if (language === "ar") {
        document.documentElement.setAttribute("lang", "ar");
        document.body.dir = "rtl";
        dropdowns.forEach((dropdown) => {
            dropdown.classList.remove("dropdown-menu-lg-end");
            dropdown.classList.add("dropdown-menu-lg-start");
        });
    } else {
        document.documentElement.setAttribute("lang", "en");
        document.body.dir = "ltr";
        dropdowns.forEach((dropdown) => {
            dropdown.classList.remove("dropdown-menu-lg-start");
            dropdown.classList.add("dropdown-menu-lg-end");
        });
    }
}

//* themes:  */
// function toggleTheme() {
//    // تحقق من الثيم الحالي وقم بالتبديل بين 'dark' و 'light'
// let currentTheme = document.documentElement.getAttribute("data-bs-theme");
// currentTheme = currentTheme === 'dark' ? 'light' : 'dark';

// // تغيير الثيم في الـ DOM
// document.documentElement.setAttribute("data-bs-theme", currentTheme);

// // تغيير أيقونة الثيم
// document.getElementById("theme-icon").className = currentTheme === 'dark' ? 'fas fa-sun' : 'fas fa-moon';

// // تخزين الثيم الجديد في Local Storage
// localStorage.setItem("theme", currentTheme);


// }

// استعادة اللغة المخزنة عند تحميل الصفحة
window.onload = function() {
    const savedLanguage = localStorage.getItem("language") || "en"; // استخدام اللغة المحفوظة أو الافتراضية (en)
    setLanguage(savedLanguage);

    // // استعادة ثيم المخزن عند تحميل الصفحة
    // const savedTheme = localStorage.getItem("theme") || 'dark'; // استخدام الثيم المخزن أو الافتراضي (dark)

    // // تعيين الثيم على الصفحة
    // document.documentElement.setAttribute("data-bs-theme", savedTheme);

    // // تحديث أيقونة الثيم بناءً على الثيم المخزن
    // document.getElementById("theme-icon").className = savedTheme === 'dark' ? 'fas fa-sun' : 'fas fa-moon';

};
